import { OrdersPanel } from '@/components/patient/orders/orders-panel';
import type { Order } from '@/types/order';

const mockOrders: Order[] = [
  {
    id: 'ORD001',
    externalOrderId: 'ClH6A0xTUYS-bgJa',
    patientId: '1',
    patientName: 'John Smith',
    patientDob: '1985-03-15',
    orderName: 'CGM & Supplies',
    orderType: 'DME',
    status: 'on_track',
    statusUpdated: '2026-01-19',
    orderAge: '9 days',
    items: [
      {
        id: 'LI001',
        description: 'Supply allowance for non-adjunctive CGM, includes all supplies and accessories, 1 month supply',
        hcpcsCode: 'A4239',
        product: 'Freestyle Libre 3 sensors',
        quantity: 2,
      },
    ],
    stage: 'eligibility',
    subStatus: 'in_progress',
    referringPractitioner: null,
    referringFacility: null,
    dateCreated: '2026-01-10',
    lastUpdated: '2026-01-19',
    documents: [],
    notes: [],
  },
  {
    id: 'ORD002',
    externalOrderId: 'Xk9B2mWqR7Lp-dNfE',
    patientId: '1',
    patientName: 'John Smith',
    patientDob: '1985-03-15',
    orderName: 'CPAP Equipment',
    orderType: 'DME',
    status: 'missing_info',
    statusUpdated: '2026-01-18',
    orderAge: '5 days',
    items: [
      {
        id: 'LI002',
        description: 'Continuous positive airway pressure (CPAP) device with humidifier and tubing',
        hcpcsCode: 'E0601',
        product: 'ResMed AirSense 11 AutoSet',
        quantity: 1,
      },
      {
        id: 'LI003',
        description: 'Replacement supplies for CPAP device — mask, cushion, headgear, tubing, and filters',
        hcpcsCode: 'A7030',
        product: 'ResMed F20 Full Face Mask Kit',
        quantity: 3,
      },
    ],
    stage: 'validation',
    subStatus: 'awaiting_response',
    referringPractitioner: 'Dr. Sarah Chen',
    referringFacility: 'Pacific Northwest Sleep Center',
    dateCreated: '2026-01-15',
    lastUpdated: '2026-01-18',
    documents: [],
    notes: [],
  },
  {
    id: 'ORD006',
    externalOrderId: 'Wq2L9nRtY6Km-pHsD',
    patientId: '1',
    patientName: 'John Smith',
    patientDob: '1985-03-15',
    orderName: 'Wheelchair',
    orderType: 'DME',
    status: 'on_track',
    statusUpdated: '2026-01-24',
    orderAge: '4 days',
    items: [
      { id: 'LI006', description: 'Lightweight folding wheelchair', hcpcsCode: 'K0004', product: 'Invacare Tracer SX5', quantity: 1 },
    ],
    stage: 'qualification',
    subStatus: 'in_progress',
    referringPractitioner: null,
    referringFacility: null,
    dateCreated: '2026-01-20',
    lastUpdated: '2026-01-24',
    documents: [],
    notes: [],
  },
  {
    id: 'ORD003',
    externalOrderId: 'Qw3F8nVtM1Hy-jKsR',
    patientId: '1',
    patientName: 'John Smith',
    patientDob: '1985-03-15',
    orderName: 'Nebulizer Supplies',
    orderType: 'DME',
    status: 'completed',
    statusUpdated: '2026-01-05',
    orderAge: '35 days',
    items: [
      {
        id: 'LI004',
        description: 'Nebulizer, durable, glass or autoclavable plastic, bottle type',
        hcpcsCode: 'E7000',
        product: 'Philips InnoSpire Go Portable Mesh Nebulizer',
        quantity: 1,
      },
    ],
    stage: 'complete',
    subStatus: 'completed',
    referringPractitioner: 'Dr. Michael Torres',
    referringFacility: 'Cascade Pulmonary Associates',
    dateCreated: '2025-12-01',
    lastUpdated: '2026-01-05',
    documents: [],
    notes: [],
  },
  {
    id: 'ORD004',
    externalOrderId: 'Jv7G3bCxZ1Np-qEwF',
    patientId: '1',
    patientName: 'John Smith',
    patientDob: '1985-03-15',
    orderName: 'CGM & Supplies',
    orderType: 'DME',
    status: 'completed',
    statusUpdated: '2026-01-23',
    orderAge: '5 days',
    items: [
      { id: 'LI004b', description: 'CGM receiver unit', hcpcsCode: 'A4226', product: 'Dexcom G7 Receiver', quantity: 1 },
    ],
    stage: 'complete',
    subStatus: 'completed',
    referringPractitioner: 'Dr. Sarah Chen',
    referringFacility: 'Pacific Northwest Medical Group',
    dateCreated: '2026-01-18',
    lastUpdated: '2026-01-23',
    documents: [],
    notes: [],
  },
  {
    id: 'ORD005',
    externalOrderId: 'Tn5F8kPwV3Qr-mXaB',
    patientId: '1',
    patientName: 'John Smith',
    patientDob: '1985-03-15',
    orderName: 'Aerosol Mask',
    orderType: 'DME',
    status: 'completed',
    statusUpdated: '2026-01-25',
    orderAge: '3 days',
    items: [
      { id: 'LI005', description: 'Pediatric aerosol mask', hcpcsCode: 'A7015', product: 'Hudson RCI Dragon Mask', quantity: 2 },
    ],
    stage: 'complete',
    subStatus: 'completed',
    referringPractitioner: 'Dr. James Park',
    referringFacility: 'Summit Health Clinic',
    dateCreated: '2026-01-22',
    lastUpdated: '2026-01-25',
    documents: [],
    notes: [],
  },
  {
    id: 'ORD007',
    externalOrderId: 'Pk1N5eGwB9Ms-tVrJ',
    patientId: '1',
    patientName: 'John Smith',
    patientDob: '1985-03-15',
    orderName: 'Wheelchair',
    orderType: 'DME',
    status: 'completed',
    statusUpdated: '2026-01-27',
    orderAge: '1 day',
    items: [
      { id: 'LI007', description: 'Transport wheelchair', hcpcsCode: 'K0001', product: 'Medline Ultralight Transport', quantity: 1 },
    ],
    stage: 'complete',
    subStatus: 'completed',
    referringPractitioner: 'Dr. Lisa Wong',
    referringFacility: 'Riverside Rehabilitation Center',
    dateCreated: '2026-01-26',
    lastUpdated: '2026-01-27',
    documents: [],
    notes: [],
  },
  {
    id: 'ORD008',
    externalOrderId: 'Zm8Q4hIxC2Ot-uWnL',
    patientId: '1',
    patientName: 'John Smith',
    patientDob: '1985-03-15',
    orderName: 'CGM & Supplies',
    orderType: 'DME',
    status: 'completed',
    statusUpdated: '2026-01-28',
    orderAge: '1 day',
    items: [
      { id: 'LI008', description: 'CGM transmitter', hcpcsCode: 'A4238', product: 'Dexcom G7 Transmitter', quantity: 1 },
    ],
    stage: 'complete',
    subStatus: 'completed',
    referringPractitioner: 'Dr. Michael Torres',
    referringFacility: 'Cascade Endocrinology',
    dateCreated: '2026-01-28',
    lastUpdated: '2026-01-28',
    documents: [],
    notes: [],
  },
  {
    id: 'ORD009',
    externalOrderId: 'Hy4M6dFvA8Lr-sUtK',
    patientId: '1',
    patientName: 'John Smith',
    patientDob: '1985-03-15',
    orderName: 'Aerosol Mask',
    orderType: 'DME',
    status: 'completed',
    statusUpdated: '2026-01-26',
    orderAge: '2 days',
    items: [
      { id: 'LI009', description: 'Adult aerosol mask with tubing', hcpcsCode: 'A7015', product: 'Teleflex Micro Mist Nebulizer', quantity: 3 },
    ],
    stage: 'complete',
    subStatus: 'completed',
    referringPractitioner: null,
    referringFacility: null,
    dateCreated: '2026-01-24',
    lastUpdated: '2026-01-26',
    documents: [],
    notes: [],
  },
  {
    id: 'ORD010',
    externalOrderId: 'Bq3R7wLtN5Gk-zPcJ',
    patientId: '1',
    patientName: 'John Smith',
    patientDob: '1985-03-15',
    orderName: 'CGM & Supplies',
    orderType: 'DME',
    status: 'completed',
    statusUpdated: '2026-02-02',
    orderAge: '3 days',
    items: [
      { id: 'LI010', description: 'CGM sensor pack', hcpcsCode: 'A4239', product: 'Freestyle Libre 3 Sensor 14-Day', quantity: 4 },
    ],
    stage: 'complete',
    subStatus: 'completed',
    referringPractitioner: 'Dr. Sarah Chen',
    referringFacility: 'Pacific Northwest Medical Group',
    dateCreated: '2026-01-30',
    lastUpdated: '2026-02-02',
    documents: [],
    notes: [],
  },
];

export default async function OrdersPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id: _id } = await params;
  return <OrdersPanel orders={mockOrders} />;
}
